language: go

go:
 - 1.8

before_script:
 - go get github.com/mattn/goveralls

script:
 - $HOME/gopath/bin/goveralls -service=travis-ci
 - go test $(go list ./... | grep -v /vendor/) -cover
 - go test $(go list ./... | grep -v /vendor/) -cover -bench=. -benchmem
